version: "3.8"

services:
  django:
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "python /usr/src/componentor/manage.py makemigrations &&
      python manage.py migrate &&
      python /usr/src/componentor/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/componentor
    ports:
      - 8000:8000
