# Generated by Django 4.2.1 on 2023-06-04 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblypart',
            name='part_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AddConstraint(
            model_name='assemblypart',
            constraint=models.UniqueConstraint(fields=('assembly', 'part'), name='unique_part_in_assembly'),
        ),
    ]
