name: CI

on: [push, pull_request]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: ${{ secrets.DEBUG }}
  DB_ENGINE: ${{ secrets.DB_ENGINE }}
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  tests:
    name: Run linter and tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]

    steps:
      - name: Check-out repo
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install

      - name: Run linter
        run: |
          make lint

      - name: Run tests
        run: |
          make test

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v4.0.0
        with:
          coverageCommand: make test-coverage
          debug: true